name: customer_information_analysis
channels:
  - conda-forge
dependencies:
  - python=3.12.5
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - sqlalchemy
  - mysql-connector-python
  - kaggle
  - pip:
    - python-dotenv
    - mkdocs
    - -e .